campingforall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from weather.views import weatherview

from . import views
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    authenticate_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('destination/', include('destination.urls', 'destination')),
    path('authenticate', authenticate_view, name="authenticate"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('googlemap/', views.Calc_dist_view, name="googlemap"),
    path('weather/', weatherview, name="weather"),





]

# this means that if we are in development mode
# what it do is that it tells like where are our static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

destination/urls.py
from django.urls import path
from destination.views import(
    
    create_destination_view,
    description_view,
    edit_description_view,
)

app_name = 'destination'

urlpatterns = [
    path('create/', create_destination_view, name="create"),
    path('<slug>/', description_view, name="description"),
    path('<slug>/edit', edit_description_view, name="edit"),

]

weather/urls.py
from django.urls import path
from .views import weatherview
from . import views

app_name = 'weather'

urlpatterns = [
    path('weather/', views.weatherview, name='weatherview'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Email Address Required")
        if not username:
            raise ValueError("Username Required")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            )
        
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
            )

        user.is_admin = True
        user.is_staff = True
        user.is_supervisor = True
        user.save(using=self._db)
        return user



# thats what we are creating a user model
class Account(AbstractBaseUser):
    email                    = models.EmailField(verbose_name="email", max_length=60,unique=True)
    username                 = models.CharField(max_length=30,unique=True)
    date_joined              = models.DateTimeField(verbose_name='date joined',auto_now=True)
    last_login               = models.DateTimeField(verbose_name='last login',auto_now=True)
    is_admin                 = models.BooleanField(default=False)
    is_staff                 = models.BooleanField(default=False)
    is_supervisor            = models.BooleanField(default=False)
    is_active                = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from account.models import Account
from django.contrib.auth import authenticate

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text='Valid Email Address Needed')

    class Meta:
        model = Account
        fields = ("email", "username", "password1", "password2")



class AccAuthenticateForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')
    
    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid Login")



class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email','username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" is already in use' % email)
    
    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username
            raise forms.ValidationError('username "%s" is already in use' % username)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from account.forms import RegistrationForm, AccAuthenticateForm, AccountUpdateForm
from destination.models import BlogPost
# Create your views here.

def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('index')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'accounts/register.html', context)



def logout_view(request):
    logout(request)
    return redirect('index')


def login_view(request):
    context = {}
    user = request.user

    if user.is_authenticated:
        return redirect('index')

    if request.POST:
        form = AccAuthenticateForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('index')
    else:
        form = AccAuthenticateForm()

    context['login_form'] = form
    return render(request, 'accounts/login.html',context)
        

def account_view(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = AccountUpdateForm(
            initial = {
                "email": request.user.email,
                "username":request.user.username,
                }
        )
    context['account_form'] = form
# a variable which will store all of the posts into the system
    campsites = BlogPost.objects.filter(author = request.user)
    context['campsites'] = campsites


    return render(request, 'accounts/account.html',context)


def authenticate_view(request):
    return render(request, 'accounts/authenticate.html', {})

account/templates/accounts/account.html
{% extends 'base.html'%}

{% block title%} Account {% endblock%}

{%block content%}

<style type="text/css">
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="username"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }      
</style>


<form class="form-signin" method="post">
    {% csrf_token %}
    <div class="column">
      <img class ="mx-auto d-block" src="/static/images/logo.png" alt="image"/>
    </div>

    <h1 class="h3 mb-3 fw-normal">Account</h1>

    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus value={{account_form.initial.email}}>
    <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required value="{{account_form.initial.username}}">

        {% for field in account_form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: darkred;"> {{error}}</p>
                {% endfor %}
            </p>  
        {% endfor %}

        {% if account_form.non_field_errors %}
            <div style="color: brown;">
                <p>{{account_form.non_field_errors}}</p>
            </div>
        {% endif %}

    <button class="w-100 btn btn-lg btn-primary" type="submit">Save Changes</button>
  </form>







<!-- <form method="post">
    {% csrf_token %}
        {% for field in account_form %}
            <p>
                {{field.label_tag}}
                {{field}}

                {% if field.help_text %}
                    <small style="color: grey;">{{field.help_text}}</small>
                {% endif %}
            </p>
        {% endfor %}

        {% for field in account_form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: darkred;"> {{error}}</p>
                {% endfor %}
            </p>  
        {% endfor %}

        {% if account_form.non_field_errors %}
            <div style="color: brown;">
                <p>{{account_form.non_field_errors}}</p>
            </div>
        {% endif %}

    <button type="submit">Update Changes</button>
</form> -->

<div class="container">
    <div class="row">
        <div class="campsites">
            <h3>campsites</h3>
            {% if campsites %}
            <ul>
                {% for post in campsites %}
                    <a href="{% url 'destination:description' post.slug %}" style="text-decoration: none;">
                        <li class="list-group-item">{{post}}</li>
                    </a>
                {% endfor %}
            </ul>
            {% else %}
                <p>No Campsites Displayed by this user <a href="{% url 'destination:create' %}">Here</a></p>
            {% endif %}
        </div>

    </div>
</div>

<footer>
    <hr>
  
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2>&copy; Camping Overload | 2021</h2>
    </div>
  </footer>

{%endblock content%}

account/templates/accounts/authenticate.html
{% extends 'base.html'%}

{% block title%} Authenticate {% endblock%}

{%block content%}

<div class="container">
    <div class="d-flex flex-column">
        <p class="m-auto">To Access this, User must Authenticate First</p>
        <p class="m-auto"></p>
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a> 

    </div>
</div>



{%endblock content%}

account/templates/accounts/login.html
{% extends 'base.html'%}

{% block title%} Login {% endblock%}

{%block content%}
<!-- bootstrap Signin example theme -->
<style type="text/css">
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }      
</style>


<form class="form-signin" method="post">
    {% csrf_token %}
    <div class="column">
      <img class ="mx-auto d-block" src="/static/images/logo.png" alt="image"/>
    </div>

    <h1 class="h3 mb-3 fw-normal">Log in</h1>

    <label for="inputEmail" class="visually-hidden">Email address</label>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="visually-hidden">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

        {% for field in login_form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: darkred;"> {{error}}</p>
                {% endfor %}
            </p>  
        {% endfor %}

        {% if login_form.non_field_errors %}
            <div style="color: brown;">
                <p>{{login_form.non_field_errors}}</p>
            </div>
        {% endif %}

    <button class="w-100 btn btn-lg btn-primary" type="submit">Log in</button>
  </form>

  <footer>
    <hr>
  
    <div class="text-center">
        <h2>&copy; Camping Overload | 2021</h2>
    </div>
  </footer>

{%endblock content%}

account/templates/accounts/register.html
{% extends 'base.html'%}

{% block title%} Register {% endblock%}

{%block content%}


<style type="text/css">
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }      
</style>


<form class="form-signin" method="post">
    {% csrf_token %}
    

    <div class="column">
      <img class ="mx-auto d-block" src="/static/images/logo.png" alt="image"/>
    </div>

    <h1 class="h3 mb-3 fw-normal">Register</h1>

    <label for="inputEmail" class="visually-hidden">Email address</label>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

    <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>

    <label for="inputPassword" class="visually-hidden">Password</label>
    <input type="password1" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

    <input type="password2" name="password2" id="inputPassword2" class="form-control" placeholder="ConfirmPassword" required>


        {% for field in registration_form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: darkred;"> {{error}}</p>
                {% endfor %}
            </p>  
        {% endfor %}

        {% if registration_form.non_field_errors %}
            <div style="color: brown;">
                <p>{{registration_form.non_field_errors}}</p>
            </div>
        {% endif %}

    <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
  </form>






<!-- <h2>Register</h2>
<form method="post"> -->
    <!-- thats used for making the form to work properly -->
    <!-- {% csrf_token %}

    {% for field in registration_form %}
        <p>
            {{field.label_tag}}
            {{field}}

            {% if field.help_text %}
                <small>{{field.help_text}}</small>
            {% endif %}

            {% for error in field.errors %}
                <p style="color: darkred;"> {{error}}</p>
            {% endfor %}    

        </p>
    {% endfor %} -->


    <!-- <button type="submit">Register</button>

</form> -->

<footer>
  <hr>

  <div class="text-center">
      <h2>&copy; Camping Overload | 2021</h2>
  </div>
</footer>

{%endblock content%}