campingforall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from weather.views import weatherview

from . import views
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    authenticate_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('destination/', include('destination.urls', 'destination')),
    path('authenticate', authenticate_view, name="authenticate"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('googlemap/', views.Calc_dist_view, name="googlemap"),
    path('weather/', weatherview, name="weather"),





]

# this means that if we are in development mode
# what it do is that it tells like where are our static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

destination/urls.py
from django.urls import path
from destination.views import(
    
    create_destination_view,
    description_view,
    edit_description_view,
)

app_name = 'destination'

urlpatterns = [
    path('create/', create_destination_view, name="create"),
    path('<slug>/', description_view, name="description"),
    path('<slug>/edit', edit_description_view, name="edit"),

]

weather/urls.py
from django.urls import path
from .views import weatherview
from . import views

app_name = 'weather'

urlpatterns = [
    path('weather/', views.weatherview, name='weatherview'),
]

destination/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver



# Create your models here.

def upload_location(instance,filename, **kwargs):
    file_path = 'destination/{author_id}/{title}-{filename}'.format(
            author_id=str(instance.author.id), title=str(instance.title), filename=filename
        )
    return file_path

class BlogPost(models.Model):
    title               = models.CharField(max_length=50, null=False, blank=False)
    body                = models.TextField(max_length=5000, null=False, blank=False)
    image               = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published      = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated        = models.DateTimeField(auto_now=True,verbose_name="date updated")
    author              = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                = models.SlugField(blank=True, unique=True)

    # testing auto_now feature


    def __str__(self):
        return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)



# new model for comment and review for each destination post
# new one

# class Comment(models.Model):
#     post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name="comments")
#     name = models.CharField(max_length=50)
#     email = models.EmailField()
#     content = models.TextField()
#     publish = models.DateTimeField(auto_now_add=True)
#     status = models.BooleanField(default=True)

#     class Meta:
#         ordering = ("publish",)

#     def __str__(self):
#         return f"comment by {self.name}"

destination/forms.py
from django import forms
from destination.models import BlogPost

# define here now

class CreateDestinationForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateDestinationForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']
    
    def save(self, commit=True):
        campsites = self.instance
        campsites.title = self.cleaned_data['title']
        campsites.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            campsites.image = self.cleaned_data['image']
        if commit:
            campsites.save()
        return campsites



# new model for comment and review for each destination post
# new one

# class NewCommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ('name', 'email', 'content')
#         widgets = {
#             "name": forms.TextInput(attrs={"class": "col-sm-12"}),
#             "email": forms.TextInput(attrs={"class": "col-sm-12"}),
#             "content": forms.Textarea(attrs={"class": "form-control"}),
#         }

destination/views.py
from django.shortcuts import render, redirect, get_object_or_404
from destination.models import BlogPost
from destination.forms import CreateDestinationForm, UpdateDestinationForm
from account.models import Account
from django.db.models import Q

# Create your views here.

def create_destination_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('authenticate')
    
    form = CreateDestinationForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateDestinationForm()

    context['form'] = form


    return render(request, "destination/create_destination.html", context)


def description_view(request, slug):

    context = {}
    campsites = get_object_or_404(BlogPost, slug=slug)
    context['campsites'] = campsites

    return render(request, 'destination/description.html',context)


def edit_description_view(request, slug):
    contet = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("authenticate")
    
    campsites = get_object_or_404(BlogPost, slug=slug)
    if request.POST:
        form = UpdateDestinationForm(request.POST or None, request.FILES or None, instance=campsites)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            campsites = obj
    form = UpdateDestinationForm(
        initial={
            "title": campsites.title,
            "body": campsites.body,
            "image":campsites.image,
        }
    )

    context['form'] = form
    return render(request, 'destination/edit_campsites', context)


# using this query for the search bar
def destination_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()
        
    for post in posts:
        queryset.append(post)
    return list(set(queryset))




# new model for comment and review for each destination post
# new one

destination/templates/destination/create_destination.html
{% extends 'base.html'%}

{% block title%} destination {% endblock%}

{%block content%}

<style type="text/css">
    .form{
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
    
    .submit_button{
        max-width: 198px;
    }

</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="form" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" required>

                </div>
                <p></p>
                <p></p>
                <div class="form-group">
                    <label for="id_body">Description</label>
                    <textarea class="form-control" rows="10" type="text" name="body" id="id_body" required>
                    </textarea>

                </div>
                <p></p>
                <p></p>

                <div class="form-group">
                    <label for="id_image">Image</label>
                    <input type="file"  name="image" id="id_image" accept="image/*" required>

                </div>

                <p></p>
                <p></p>

                <button class="w-100 btn btn-lg btn-primary" type="submit">Post</button>
            </form>
        </div>
    </div>
</div>

<footer>
    <hr>
  
    <div class="text-center">
        <h2>&copy; Camping Overload | 2021</h2>
    </div>
  </footer>

{%endblock content%}

destination/templates/destination/description.html
{% extends 'base.html'%}


{%block content%}

<!-- <style type="text/css">
    
    .container{
        padding: 17px;
    }

</style> -->

<div class="container">
    <div class="row">
        <div class="card m-auto">
            <img class="card-img-top" src="{{campsites.image.url}}">
            <div>
                <h2 class="card-title">{{campsites.title}}</h2>
                <p class="card-text">{{campsites.body}}</p>
            </div>
            <div class="card-footer">
                Updated on {{campsites.date_updated}} by {{campsites.author}}
            </div>
        </div>
    </div>
</div>

<footer>
    <hr>
  
    <div class="text-center">
        <h2>&copy; Camping Overload | 2021</h2>
    </div>
  </footer>

{% endblock content%}

destination/templates/destination/edit_campsites.html
{% extends 'base.html'%}


{%block content%}

{% endblock content%}